# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data da Coleta')),
                ('precipitacao', models.FloatField(verbose_name='Precipita\xe7\xe3o')),
                ('temperatura_min', models.FloatField(verbose_name='Temperatura M\xednima')),
                ('temperatura_max', models.FloatField(verbose_name='Temperatura M\xe1xima')),
                ('umidade_media', models.FloatField(verbose_name='umidade M\xe9dia')),
            ],
            options={
                'verbose_name': 'Previs\xe3o',
                'verbose_name_plural': 'Previs\xf5es',
            },
        ),
    ]
