# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161203_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amostra',
            old_name='momento_coleta',
            new_name='data',
        ),
    ]
