# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161203_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='insolacao',
            field=models.FloatField(default=0, verbose_name='Insola\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amostra',
            name='precipitacao',
            field=models.FloatField(default=0, verbose_name='Precipita\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amostra',
            name='data',
            field=models.DateField(unique=True, verbose_name='Data da Coleta'),
        ),
    ]
